[package]
name = "skjra"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = { version = "0", default-features = false, features = ["clock"] }
endringer = "0"
iced = "0.14"
rfd = "0.17"
petgraph = "0"
